
#g++ main.cpp -o ir_wave_tool $(pkg-config sndfile --cflags --libs)


CC:=g++
exe:=ir_wave_tool
obj:=main.o

all:$(obj)
 $(CC) -o $(exe) $(obj)  
%.o:%.c
 $(CC) -c $^ -o $@

.PHONY:clean
clean:
 rm -rf $(obj) $(exe)
